{% set name = "nexusformat" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 603aa9938a35091f92ecb56e22dd42ea30603bfe013cdc5a8cad71ba2694f8fb

build:
  number: 0
  entry_points:
    - nxstack=nexusformat.scripts.nxstack:main
    - nxduplicate=nexusformat.scripts.nxduplicate:main
    - nexusformat=nexusformat.scripts.nexusformat:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - h5py
    - ipython
    - numpy
    - scipy

test:
  imports:
    - nexusformat
    - nexusformat.nexus
    - nexusformat.scripts
  commands:
    - nxstack --help
    - nxduplicate --help
    - nexusformat --help

about:
  home: https://nexpy.github.io/nexpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'nexusformat: Python API to access NeXus data'
  doc_url: https://nexpy.github.io/nexpy
  dev_url: https://github.com/nexpy/nexusformat
